//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bets")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub event_id: i32,
    pub option_id: i32,
    pub quantity: i32,
    #[sea_orm(column_type = "Decimal(Some((4, 2)))")]
    pub price_per_share: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub total_amount: Decimal,
    pub status: String,
    pub placed_at: DateTime,
    pub settled_at: Option<DateTime>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub payout_amount: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::event_options::Entity",
        from = "Column::OptionId",
        to = "super::event_options::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EventOptions,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Events,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::event_options::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventOptions.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
