//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "event_options")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub event_id: i32,
    pub option_text: String,
    #[sea_orm(column_type = "Decimal(Some((4, 2)))")]
    pub current_price: Decimal,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    pub total_backing: Decimal,
    pub is_winning_option: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
    #[sea_orm(has_many = "super::orders::Entity")]
    Orders,
    #[sea_orm(has_many = "super::trades::Entity")]
    Trades,
    #[sea_orm(has_many = "super::user_positions::Entity")]
    UserPositions,
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::trades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trades.def()
    }
}

impl Related<super::user_positions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPositions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
