//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub category: String,
    pub status: String,
    pub end_time: DateTime,
    #[sea_orm(column_type = "Decimal(Some((8, 2)))")]
    pub min_bet_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub max_bet_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    pub total_volume: Decimal,
    pub image_url: String,
    pub created_by: i32,
    pub resolved_by: i32,
    pub winning_option_id: i32,
    #[sea_orm(column_type = "Text")]
    pub resolution_note: String,
    pub resolved_at: DateTime,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::event_options::Entity")]
    EventOptions,
    #[sea_orm(has_many = "super::orders::Entity")]
    Orders,
    #[sea_orm(has_many = "super::trades::Entity")]
    Trades,
    #[sea_orm(has_many = "super::user_positions::Entity")]
    UserPositions,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ResolvedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
}

impl Related<super::event_options::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventOptions.def()
    }
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::trades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trades.def()
    }
}

impl Related<super::user_positions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPositions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
