//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "trades")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub event_id: i32,
    pub option_id: i32,
    pub buyer_id: i32,
    pub seller_id: i32,
    pub buy_order_id: String,
    pub sell_order_id: String,
    #[sea_orm(column_type = "Decimal(Some((20, 8)))")]
    pub price: Decimal,
    pub quantity: i32,
    #[sea_orm(column_type = "Decimal(Some((20, 8)))")]
    pub total_amount: Decimal,
    pub timestamp: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::event_options::Entity",
        from = "Column::OptionId",
        to = "super::event_options::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    EventOptions,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Events,
    #[sea_orm(
        belongs_to = "super::orders::Entity",
        from = "Column::BuyOrderId",
        to = "super::orders::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Orders2,
    #[sea_orm(
        belongs_to = "super::orders::Entity",
        from = "Column::SellOrderId",
        to = "super::orders::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Orders1,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::BuyerId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::SellerId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Users1,
}

impl Related<super::event_options::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventOptions.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
